### ISSUE TITLE
Typos in sample_profiles.yml and README

### ISSUE THREAD

**Issue by cch0** [aws-samples/dbt-glue#179]
### Describe the bug
Typos in `sample_profiles.yaml` results in incorrect configuration.

- `type` should be `glue` but is `awsglue`.
- `session_provisionning_timeout_in_seconds` should have been `session_provisioning_timeout_in_seconds`.

### Steps To Reproduce

1. Execute `dbt init {project_name}` 
2. Observe that in `profiles.yml` file, `type` is set to `awsglue` and `session_provisionning_timeout_in_seconds` is being used.

### Expected behavior
1. `type` should be `glue`.
2. `session_provisioning_timeout_in_seconds` should be used.

### Screenshots and log output
Output of `dbt init tmp02`

```
tmp02:
  outputs:

    dev:
      type: awsglue
      role_arn: arn:aws:iam::<awss account>:role/GlueInteractiveSessionRole
      region: eu-west-1
      workers: 5
      worker_type: G.1X
      schema: "dbt_test_{{ var('_dbt_random_suffix') }}"
      session_provisionning_timeout_in_seconds: 20

    prod:
      type: awsglue
      role_arn: arn:aws:iam::<aws account>:role/GlueInteractiveSessionRole
      region: eu-west-1
      workers: 5
      worker_type: G.1X
      schema: "dbt_test_{{ var('_dbt_random_suffix') }}"
      session_provisionning_timeout_in_seconds: 20

  target: dev
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.6
  - latest:    1.5.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - glue:  1.4.21 - Up to date!
  - spark: 1.4.2  - Update available!
```

**The operating system you're using:**

**The output of `python --version`:**

```
Python 3.11.3
```
