### ISSUE TITLE
Small file output

### ISSUE THREAD

**Issue by rickiesmooth** [aws-samples/dbt-glue#223]
### Describe the bug
I'm running a simple model with the following config:
```sql
# silver_pageviews.sql
{{ config(
    partition_by = ['team_id', 'date_day'],
    file_format = 'parquet',
) }}
```
and it outputs the following files in a partition `silver_pageviews/team_id=d5eb5eca-c8b2-4711-9d0a-f07ea0ad7b31/date_day=2023-08-23/`
| Name | Type | Last modified | Size | Storage class |
| ---- | ---- | ------------- | ---- | ------------- |
| part-00000-64241151-b482-411e-8885-6ad01209fb14_00000.c000.snappy.parquet | parquet | August 24, 2023, 10:24:27 (UTC+02:00) | 4.6 KB | Standard |
| part-00001-64241151-b482-411e-8885-6ad01209fb14_00000.c000.snappy.parquet | parquet | August 24, 2023, 10:24:27 (UTC+02:00) | 4.5 KB | Standard |

```yml
# profile.yml
demo:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: demo
      role_arn: "{{ env_var('DBT_ROLE_ARN') }}"
      region: us-east-1
      workers: 2
      worker_type: G.1X
      schema: "demo"
      database: "demo"
      session_provisioning_timeout_in_seconds: 120
      location: "{{ env_var('DBT_S3_LOCATION') }}"
```      

### Steps To Reproduce
I'm using the above configuration, and the input Glue Table's S3 location is partitioned like 
`events/2023/08/23/16/` 
which contain a number of small parquet files. 

### Expected behavior
I expect dbt-glue to output only one parquet file per partition (similar to sparks `coalesce(1)`).

### System information
**The output of `dbt --version`:**
```
08:23:12  Running with dbt=1.6.1
08:23:13  Registered adapter: glue=1.6.1
```

**The operating system you're using:**

```
  python-version: 3.8
```
