### ISSUE TITLE
Glue 4.0 only succeeds first run

### ISSUE THREAD

**Issue by rickiesmooth** [aws-samples/dbt-glue#228]
### Describe the bug
Glue doesn't recognize existing delta table produced by `dbt-glue`

### Steps To Reproduce
* Configure a dbt-glue project using `datalake_formats: delta` , eg:
```yml
demo:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: demo
      role_arn: "{{ env_var('DBT_ROLE_ARN') }}"
      region: us-east-1
      glue_version: "4.0"
      workers: 2
      worker_type: G.1X
      schema: "demo"
      database: "demo"
      session_provisioning_timeout_in_seconds: 120
      location: "{{ env_var('DBT_S3_LOCATION') }}"
      datalake_formats: delta
      conf: "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
      extra_py_files: "/opt/aws_glue_connectors/selected/datalake/delta-core_2.12-2.1.0.jar"
```

```sql
{{ config(
    incremental_strategy='insert_overwrite',
    partition_by=['team_id', 'date_day'],
    file_format='delta',
) }}

with new_events as (

    select * from {{ ref('events') }}

    {% if is_incremental() %}
    where date_day >= date_add(current_date, -1)
    {% endif %}

)

select
    user_id,
    max(date_day) as last_seen,
    current_date() as dt

from events
group by 1
```

* Run dbt-glue project to create the initial delta table
* Run dbt-glue project after initial delta table is created and it returns the following error:
```bash
07:23:29      '''), AnalysisException: Cannot create table ('`demo`.`silver_pageviews`'). The associated location ('s3://prod-pipeline-data-lake-output/demo/silver_pageviews') is not empty but it's not a Delta table
```
* navigate to `s3://prod-pipeline-data-lake-output/demo/silver_pageviews` and observe there's a `_delta_log` directory in the location.

### Expected behavior
Glue recognizes associated location as delta table

### System information
**The output of `dbt --version`:**
```
07:20:35  Running with dbt=1.6.1
07:[20](https://github.com/rickiesmooth/trackagree/actions/runs/6006491699/job/16298048718#step:6:21):35  Registered adapter: glue=1.6.2
```

**The operating system you're using:**

**The output of `python --version`:**
