### ISSUE TITLE
Iceberg tables are not created with partitions

### ISSUE THREAD

**Issue by nbenezri** [aws-samples/dbt-glue#501]
### Describe the bug
Iceberg tables are not created with partitions.

### Steps To Reproduce
I went with the most basic SQL I could think of:

```
{{ config(
    materialized='incremental',
    incremental_strategy='append',
    table_type='iceberg',
    partitioned_by=['s_day']
) }}
WITH
prq AS (
    SELECT
        1                  AS user_id,
        DATE('2024-01-01') AS file_day,
        DATE('2024-01-01') AS s_day
)

SELECT *
FROM prq
```

### Expected behavior
`dbt-glue` should create the iceberg table as partitioned by `s_day`.
It should look like:
```
SHOW CREATE TABLE db.test_me;

CREATE TABLE db.test_me (
  user_id int,
  file_day date,
  stream_day date)
PARTITIONED BY (stream_day)
LOCATION 's3://bucket/db/test_me'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet',
  'write_compression'='zstd'
);
```

### Screenshots and log output
```
(dbe-python) nir dbt % dbt run --target glue_dev --select models/glue/staging/test_me.sql
16:40:20  Running with dbt=1.9.1
16:40:20  Registered adapter: glue=1.9.0
16:40:20  Found 11 models, 93 data tests, 3 sources, 631 macros
16:40:20  
16:40:20  Concurrency: 1 threads (target='glue_dev')
16:40:20  
16:40:22  1 of 1 START sql incremental model db.test_me ......................... [RUN]
16:40:23  Glue adapter: Parameter validation failed:
Invalid type for parameter Name, value: , type: <class 'jinja2.runtime.Undefined'>, valid types: <class 'str'>
16:40:36  1 of 1 OK created sql incremental model db.test_me .................... [OK in 13.65s]
16:40:36  
16:40:36  Finished running 1 incremental model in 0 hours 0 minutes and 15.41 seconds (15.41s).
16:40:36  
16:40:36  Completed successfully
16:40:36  
16:40:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

Then in Athena:
```
SHOW CREATE TABLE db.test_me;

CREATE TABLE db.test_me (
  user_id int,
  file_day date,
  stream_day date)
LOCATION 's3://bucket/db/test_me'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet',
  'write_compression'='zstd'
);
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.1
  - latest:    1.9.1 - Up to date!

Plugins:
  - glue:     1.9.0 - Up to date!
  - redshift: 1.9.0 - Up to date!
  - postgres: 1.9.0 - Up to date!
  - spark:    1.9.0 - Up to date!
  - athena:   1.8.4 - Update available!
```

**The operating system you're using:**
```
macos sequoia 15.1.1
```

**The output of `python --version`:**
```
Python 3.12.8
```

### Additional context
profile:
```
dbt:
  target: athena_dev
  outputs:
    glue_dev:
      type: glue
      role_arn: <role>
      region: us-east-1
      workers: 8
      worker_type: G.8X
      glue_version: "5.0"
      datalake_formats: iceberg
      iceberg_glue_commit_lock_table: DbtGlueLockTable
      schema: "db"
      session_provisioning_timeout_in_seconds: 300
      location: "s3://bucket"
      custom_iceberg_catalog_namespace : ""
      idle_timeout: 2
      glue_session_id: id
      glue_session_reuse: true
      conf: "spark.serializer=org.apache.spark.serializer.KryoSerializer
             --conf spark.sql.warehouse=s3://bucket/
             --conf spark.sql.defaultCatalog=glue_catalog
             --conf spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog
             --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
             --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
             --conf spark.sql.catalog.glue_catalog.lock-impl=org.apache.iceberg.aws.dynamodb.DynamoDbLockManager
             --conf spark.sql.catalog.glue_catalog.lock.table=DbtGlueLockTable
             --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
      default_arguments: "--enable-metrics=true, --enable-continuous-cloudwatch-log=true, --enable-continuous-log-filter=true, --enable-spark-ui=true, --spark-event-logs-path=s3://bucket/sparkHistoryLogs/"
```
