### ISSUE TITLE
Better handling for API throttling

### ISSUE THREAD

**Issue by moomindani** [aws-samples/dbt-glue#539]
### Describe the feature
When running dbt-glue concurrently in an account, this can hit API rate limit. The following error can occur.
```
[2025-03-28, 15:17:28 UTC] {script.py:190} INFO - 15:17:28  Glue adapter: Error in GlueCursor (session_id=dbt_glue_session_xxxxxx) execute: An error occurred (ThrottlingException) when calling the RunStatement operation (reached max retries: 10): Rate exceeded
```

### Describe alternatives you've considered
API rate limit increase is one of the possible solutions, however, it would be better to have configuration to manage retries more flexibility.

### Additional context
Currently, connection.py has the static configuration of `max_attempts` set to 10.
It is better to make this configurable.

### Who will this benefit?
Any users who use dbt-glue with high concurrency.

### Are you interested in contributing this feature?
Yes.

**Comment by lawofcycles** [comment]
This has been addressed in #642 (included in v1.10.19). The boto3 retry settings are now configurable through the dbt profile.

```yaml
outputs:
 dev:
   type: glue
   boto_retry_mode: "adaptive"       # default: "adaptive"
   boto_retry_max_attempts: 20       # default: 10
   statement_poll_interval: 1.5      # GetStatement polling interval in seconds
   # ... other settings
```

@sugichy @yotahk  I believe this issue can be closed.
