### ISSUE TITLE
v1.9.4 adapter unconditionally creates a session per model if "meta" is defined

### ISSUE THREAD

**Issue by sonya** [aws-samples/dbt-glue#547]
### Describe the bug

Previously when `glue_session_id` and `glue_session_reuse` were both set, all models were run in the same session. This was helpful for conserving resources when transformations were cheap.

In 1.9.4 a change was introduced (via #496) such that if a model had a `meta` field for any reason, the adapter would create a model-specific session.

Although I appreciate the new feature for models that require different worker allocation, it causes models with `meta` configured for unrelated reasons (e.g. documentation generation) to also create separate sessions. This forces us to choose between conserving resources and supporting custom plugins when these choices should not be related.

### Steps To Reproduce

1. Create a profile with the following configs:
```yaml
glue_adapter:
  target: dev
  outputs:
    dev:
      type: glue
      role_arn: arn:aws:iam::000000000000:role/my-role
      region: us-east-1
      workers: 10
      worker_type: G1.X
      schema: my_schema
      session_provisioning_timeout_in_seconds: 120
      glue_session_id: my-persistent-session-id
      glue_session_reuse: true
      idle_timeout: 2
      location: s3://mybucket/myprefix
      datalake_formats: iceberg
      default_arguments: "--enable-auto-scaling=true"
      conf: >
        spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog
        --conf spark.sql.defaultCatalog=glue_catalog
        --conf "spark.sql.catalog.glue_catalog.default-namespace=my_schema
        --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
        --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
```
2. Define a model with some custom properties in `meta`, e.g.
```yaml
models:
  - name: location_address
    config:
      meta:
        resource_group: Location
  - name: location_identifier
    config:
      meta:
        resource_group: Location
```

3. Run this project with v1.9.0 of the `dbt-glue` adapter. Notice that there is one session named `my-persistent-session-id`
4. Run this project with v1.9.4 of the `dbt-glue` adapter. Notice that there are two sessions named something like `my-persistent-session-id.location_address` and `my-persistent-session-id.location_identifier`

### Expected behavior

I expect there to be only a single session named `my-persistent-session-id`

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.9.4
  - latest:    1.9.4 - Up to date!

Plugins:
  - glue:      1.9.4 - Up to date!
  - snowflake: 1.9.2 - Up to date!
  - spark:     1.9.2 - Up to date!
  - athena:    1.9.3 - Up to date!
```

**The operating system you're using:**

Docker `python` image running on Fargate

**The output of `python --version`:**

Python 3.12.7
